language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: bF41cEIXY/r9MWILYMtn8iVsnnC5zs1k1KMwM2u/6iMbDYlCsrPWx/DSLPM6sveqNU1El7GJINRXItOLQKgScLvYqMcLr+KfZObJLKjxT5lsdsI/Dh2El8cXlOiOxyAI+ZrZc4seXoHnETFVqc4gaOAw7Ilvh1yjivMe3KP59sqEIicjdjJD+O4aVCo0GLehN4h09p2ICUvpZTut17y+f+KMGowoCbIG6JHIn4dSXxUgoGKYlG0svJgrT1s3D5UXxYlQPxANJe8+Pv7MqNBa+mlznpq7Ic4k4hafl/u+azZRfEOVlm4nPtQw5gx1BrSFM5taXo3gPZV1wZHIdWQPJi5ah3uj7JT/Xet0f6wgJqVxcc1NqL8IfYwQywhM3r4WKSPq4+dWuKqON0HBKJxrzvoWWVKzBJE2NSfI+chDZjLDtF6AtuLWBvP1KcpbRorni5JHoh6magRH45XeN1L0MPjeKCBfvLEA6PRz2DyOUkEF/va3uW9tQMbGPaCfaiuKdzI4iqDGA0u1zSv6oXeZpfpy+bvPiAqpYrWrm2MFB11HCX+GMeV8wqGdJX2+s0EWjGmvF5HFmxnIzlv9rRYa93jr5NhXmFUQTDG9fwO2tv1zopwTczvW89l+LJmIbiRPKDf2RGV3HC9a/WS0BfDHa0JmDuGvdoOqgbK6/fYVp/0=
  app: seepage-api
  on:
    repo: bibiqiqi/seepage-api
