language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: SumuYQYyziBXJRY+27nBhOpzZk/1tYTq7hkt7XeBnimHJcLXmYkYfa9mDl0I79jl/Wl4kU5l4IZluYdzgZFoR22eQ7eqHBAgLJpe2gmNpxi90KLDXeGqpTLLAXB4s/W2J2cxZxjWoMAEjOrhSN+6P3M9YXMDlXp4HQMF8i3VUi+JuD0WeaqJjry22jJadWjGx/yIO2RlwLLJh1zhv6l1MtRfcTkKGvAkP//bid70aIr/kP5dqqexF57WjvHu0PggSwc5IvIYYJp4Vk0RitxZx3B/S+A/cI2xXr7oaolrPA9SZjy9swVDWTvqCHzOg5t37+hJkbZ6xiqT5FZ55Zf7uD1PX8D5qa5QRsUXHP1cN9TEJgZHTrqryGrhhDv9+mDhimMY+X1yEAmnumoQo9VRKKmN8FB1LVc9LNMEv9fyoLpVHSytYbfYVFIsqmhN7pFs+ZkfRORmsGTJJMzKF3BGkzAdjOLa0ATkekK+n91Yn035Utyh9DtHsu/cWR1N7IDkxEVW9QiSjfr9KNly2wbvzrNeLeT40DWi4gqKooCfe1KhLnj4kLK70W96t1kEY28uZhDt1MnU1Y5Gtc5boxUVoklqSXCXsV8vjkuoM+THK/8alcvvPBROMWJI5hoGryWlsLPpPPy3AdyZUjkdhrNEjXuVQ4unb2JcL2fHncnQJVc=
  app: seepage-api
  on:
    repo: bibiqiqi/seepage-api
