language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: NCHna2fv4a5TWvh/jfhsED9oiroIT/jQaJtLD5tK0uhRMkAIsfd1pjm/DsNb5s2KbifczoMRC2iS4XB/NaURYxTR1oD/HakdeLrbB3Z8uBsTMapnpq9Hp3MJUSgu+90d2MPxlkn7k2g3pyeN/B3Oq131bzKpOj+IE20d/Tx48xh3/0iUQmofG7iWDq2WDgRCpCu92sY+BVwI9OY05UdyYxNyXRksA1CfdMRF1PjNU9VzqgTU37HH0twTu+n8mQtHtpFbGpt/d7kLGI9j3l58D/u4kTff4Gi2+kbqI/f8aJN9Sx3MVYvnBuebnntz3MDP2yfGI7NZd36aTrk8i1V+ACmUSYcPjaVy8z0Ad800qQOmJqnMQAI10veK2JFbuoHkIMj5/6/HRV6b86r6eLiNIPBoOzXnz5IZll2D8jNrpQorD3E2GKQIwYbcwAvjkOiaUn8Nd6kPwr5n73DxgpUY51shbAs2JxIAkSzr0zkru1+bFKZuz5BMdlSOFo0BNmbNqapRrq42EHxDvMUlMRtnMdzZoexCWSRBaWhKqpeKZU23uDETFP9jOSnxweIwHkLcMpTHXc0RObtvuqcg2L0mUEa2SSmd6QA9wdiIy5tYPyV9Rn2n7g3xcTt9Z0QZ0TaB38KwkhHqDkjNzaFMYUl0ixU1Zi1KrU6m2wXVN/l0ha8=
  app: seepage-api
  on:
    repo: bibiqiqi/seepage-api
